name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4']
        laravel: ['10.*', '11.*', '12.*', '13.*']

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2 (setup-php v2.37.2)
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Audit dependencies for known vulnerabilities
        run: composer audit

      - name: Run tests
        run: ./vendor/bin/pest
